---
- name: "Download miniforge from '{{ miniforge_release_base_url }}'"
  retries: 3
  delay: 1
  ansible.builtin.get_url:
    url: "{{ miniforge_release_base_url }}/{{ installation_script_name }}.sh"
    timeout: 10
    dest: "{{ miniforge_script_path }}"
    mode: "0664"

- name: "Deploy Mamba in a user loop"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  ansible.builtin.include_tasks: "miniforge.yaml"
