---
- name: "Download miniforge from '{{ miniforge_release_base_url }}'"
  retries: 3
  delay: 1
  ansible.builtin.get_url:
    url: "{{ miniforge_release_base_url }}/{{ installation_script_name }}.sh"
    timeout: 10
    dest: "{{ miniforge_script_path }}"
    mode: "0664"

- name: "Deploy Mamba in a user loop"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  ansible.builtin.include_tasks: "miniforge.yml"

- name: "Create environments from deployed manifests"
  when:
    - "create_envs is true"
    - "item.1 is defined"
  with_subelements:
    - "{{ users | map('combine', {'mamba_files': []}, list_merge='append') }}"
    - "mamba_files"
  ansible.builtin.include_tasks: "manifests.yml"
