---
# tasks file for playbooks/roles/miniforge

- name: "Deploy Mamba in a user loop"
  loop: "{{ usernames }}"
  loop_control:
    loop_var: loop_username
  ansible.builtin.include_tasks: "miniforge.yaml"

# - name: "Deploy environments from files for each user"
#   loop: "{{ usernames }}"
#   loop_control:
#     loop_var: loop_username
#   ansible.builtin.include_tasks: "deploy_envs.yml"

        