---
- name: "Get contents of the manifest file"
  register: manifest_content
  ansible.builtin.slurp:
    src: "{{ homedir }}/{{ file }}"

# Since the file can be named whatever, we need to extract the environment name
# as that is what the actual environment folder name will be
- name: "Extract enviroment name from manifest file"
  ansible.builtin.set_fact:
    env_name: '{{ (manifest_content.content | b64decode | from_yaml).name }}'

- name: "Display the extracted environment name"
  ansible.builtin.debug:
    msg: "{{ env_name }}"

- name: "Create environment: {{ env_name }}"
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.shell:
    cmd: "{{ homedir }}/miniforge3/bin/mamba env create -f {{ homedir }}/{{ file }}"
    executable: /bin/bash
    # ensures that the task runs only when the environment doesn't exist
    creates: "{{ homedir }}/miniforge3/envs/{{ env_name }}"
