---
# These variables are registered as host vars, for whatever deep reason
- name: "Get current user entity info"
  ansible.builtin.getent:
    database: passwd
    key: "{{ loop_username }}"
    split: ":"


- name: "Get current user home directory ({{ loop_username }}"
  ansible.builtin.set_fact:
    homedir: "{{ getent_passwd[loop_username][4] }}"

- name: "Set miniforge dir ({{ loop_username }}"
  ansible.builtin.set_fact:
    miniforge_dir: "{{ homedir }}/miniforge3"

- name: "Build miniforge bin path ({{ loop_username }})"
  ansible.builtin.set_fact:
    mamba_bin_path: "{{ miniforge_dir }}/bin/mamba"


- name: "Display miniforge script path ({{ loop_username }})"
  ansible.builtin.debug:
    msg: "{{ miniforge_script_path }}"


- name: "Install miniforge"
  become: true
  become_user: "{{ loop_username }}"
  vars:
    allow_world_readable_tmpfiles: true
  block:
    - name: "Check Mamba availability ({{ loop_username }})"
      changed_when: false
      ansible.builtin.command:
        cmd: "{{ mamba_bin_path }} info"

  rescue:
    - name: "Install miniforge in a non-interactive mode ({{ loop_username }})"
      ansible.builtin.command:
        cmd: "/bin/bash {{ miniforge_script_path }} -b"
        creates: "{{ homedir }}/miniforge3"

    - name: "Initialize Mamba/Conda ({{ loop_username }})"
      changed_when: false
      ansible.builtin.command:
        cmd: "{{ mamba_bin_path }} init"

    - name: "Check if Mamba has become available ({{ loop_username }})"
      changed_when: false
      ansible.builtin.command:
        cmd: "{{ mamba_bin_path }} info"


- name: "Deploy default .condarc if it doesn't exist already ({{ loop_username }})"
  become: true
  become_user: "{{ loop_username }}"
  block:
    - name: "Check if .condarc already exists ({{ loop_username }})"
      register: this
      failed_when: this.stat.exists is false
      ansible.builtin.stat:
        path: "{{ homedir }}/.condarc"

  rescue:
    - name: "Set default .condarc from external file if provided ({{ loop_username }})"
      when: condarc_file is defined and condarc_file != ""
      ansible.builtin.copy:
        src: "{{ condarc_file }}"
        dest: "{{ homedir }}/.condarc"
        mode: "0600"

    - name: "Set default content via .condarc ({{ loop_username }})"
      when: condarc_file is not defined or condarc_file == ""
      ansible.builtin.copy:
        dest: "{{ homedir }}/.condarc"
        content: "{{ condarc | to_nice_yaml }}"
        mode: "0600"
