---
- name: Converge
  hosts: all

  roles:
    - role: genlab.miniforge
      release_version: 24.3.0-0
      usernames:
        - alice
        - bob
      condarc:
        channels: [ conda-forge ]
      manifest_dir: "manifests"
      user_mapping_file: "deployment.yml"
