---
# you can use {{all_users | selectattr('name', 'in', mamba_users)}} to narrow down a larger list
- name: Converge
  hosts: all
  vars:
    mamba_users:
      - name: alice
        mamba_envs: [ project-alpha.yml, project-beta.yml ]
      - name: bob
        mamba_envs: [ project-beta.yml ]
      - name: charlie

  pre_tasks:
    - name: "Create test users"
      loop: [ alice, bob, charlie ]
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        create_home: true

  roles:
    - role: genlab.miniforge
      release_version: 24.3.0-0
      users: "{{ mamba_users }}"
      manifest_dir: "manifests"
      create_envs: true
      condarc:
        channels: [ conda-forge ]
